CREATE TYPE user_role AS ENUM ('STUDENT', 'EMPLOYEE', 'CANDIDATE', 'GUEST');
CREATE TYPE schedule_status AS ENUM ('SCHEDULED', 'CANCELLED', 'COMPLETED');
CREATE TYPE notification_mode AS ENUM ('PUSH_AND_INAPP', 'INAPP_ONLY', 'OFF');


CREATE TABLE users
(
    id                  UUID PRIMARY KEY,  -- UUIDv7 generated by Application
    role                user_role                                          NOT NULL,
    email               VARCHAR(255) UNIQUE                                NOT NULL,
    password_hash       VARCHAR(255)                                       NOT NULL,
    first_name          VARCHAR(100)                                       NOT NULL,
    last_name           VARCHAR(100)                                       NOT NULL,
    index_number        VARCHAR(20) UNIQUE,
    pesel               CHAR(11) UNIQUE,
    biometric_token     TEXT,                                                        -- Authorization token for FaceID/TouchID
    password_changed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_users_email ON users (email);

CREATE TABLE schedules
(
    id            UUID PRIMARY KEY, -- UUIDv7 generated by Application
    group_id      VARCHAR(50)                                        NOT NULL,
    subject_name  VARCHAR(150)                                       NOT NULL,
    lecturer_name VARCHAR(150)                                       NOT NULL,
    classroom     VARCHAR(50)                                        NOT NULL,
    start_time    TIMESTAMP WITH TIME ZONE                           NOT NULL,
    end_time      TIMESTAMP WITH TIME ZONE                           NOT NULL,
    status        schedule_status          DEFAULT 'SCHEDULED'       NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_schedules_group_time ON schedules (group_id, start_time, end_time);


CREATE TABLE user_notification_settings
(
    user_id                    UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    academic_grades            notification_mode        DEFAULT 'PUSH_AND_INAPP'  NOT NULL,
    academic_schedule_changes  notification_mode        DEFAULT 'PUSH_AND_INAPP'  NOT NULL,
    academic_cancelled_classes notification_mode        DEFAULT 'PUSH_AND_INAPP'  NOT NULL,
    financial_new_charges      notification_mode        DEFAULT 'PUSH_AND_INAPP'  NOT NULL,
    events_student             notification_mode        DEFAULT 'INAPP_ONLY'      NOT NULL,
    updated_at                 TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE outbox_events
(
    id             UUID PRIMARY KEY,
    aggregate_type VARCHAR(100)                                       NOT NULL,
    aggregate_id   VARCHAR(100)                                       NOT NULL,
    event_type     VARCHAR(100)                                       NOT NULL,
    payload        JSONB                                              NOT NULL,
    processed      BOOLEAN                  DEFAULT FALSE             NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_outbox_unprocessed_v7 ON outbox_events (id) WHERE processed = FALSE;